### ISSUE TITLE
build on python3?

### ISSUE THREAD

**Issue by nbecker** [ndarray/ndarray#25]
Is there a way to configure scons to build against an alternative python (python3.3)?

It at least needs to use /usr/include/python3.3m.  Maybe also /usr/lib64/libpython3.3m.so

**Comment by forresti** [comment]
How do you tell CMake to use Python3?

**Comment by TallJimbo** [comment]
@forresti the following works for me (on Ubuntu 14.04, using Python 3 from apt-get):
```
mkdir build-py3
cd build-py3
cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.4 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.4m.so ..
make
```

The test code doesn't run (because it's written in Python 2), so `make test` won't work.  I'll open an new issue to address that, but don't hold your breath (as you may have noticed, I don't have a whole lot of time to devote to this library anymore).

**Comment by TallJimbo** [comment]
Python 3 build works with CMake, and I plan to retire the SCons build soon.
