### ISSUE TITLE
Size seen by iterator differs from size claimed by Array

### ISSUE THREAD

**Issue by PaulPrice** [ndarray/ndarray#38]
This issue was originally found by Andreas Ritter.  It seems that the size seen by the iterator (which affects the size printed to `std::cout`) is different from the size claimed by `Array::getShape()`.  Here's a how-to-reproduce:

    #include <iostream>
    #include "ndarray.h"
    #include "ndarray/eigen.h"
    
    int main(){
        ndarray::Array<float, 3, 2> testArray = ndarray::allocate(10,10,10);
        std::cout << "testArray.getShape() = " << testArray.getShape() << std::endl;
        std::cout << "testArray[ndarray::view(0)()(1) = " << testArray[ndarray::view(0)()(1)] << std::endl;
        ndarray::Array<float, 1, 1> testView = testArray[ndarray::view(0)()(1)];
        std::cout << "testView.getShape() = " << testView.getShape() << std::endl;
        std::cout << "testView = " << testView << std::endl;
        std::cout << "Iterator-based size: " << testView.end() - testView.begin() << std::endl;
        std::cout << "testView via iterator: ";
        for (ndarray::Array<float, 1, 1>::const_iterator i = testView.begin(); i != testView.end(); ++i) {
            std::cout << *i;
        }
        std::cout << std::endl;
    
        assert(testView.end() - testView.begin() == testView.getShape()[0]);
    
        return 1;
    }

To build:

    g++ -o test_3d_ndarray -g -DLSST_HAVE_TR1=0 -DLSST_LITTLE_ENDIAN=1 -O3 -Wall -Wno-unused-function -fPIC -I$NDARRAY_DIR/include -I$EIGEN_DIR/include -I$BOOST_DIR/include test_3d_ndarray.cc

I have seen this with g++ 4.8.2 (Ubuntu 14.04) and clang++ 3.1 (MacOS 10.7), both with boost 1.55.0, Eigen 3.2 and ndarray master.

    price@neverland:~/test/andreas $ g++ -o test_3d_ndarray -g -O3 -fPIC -Indarray/include -I$EIGEN_DIR/include -I$BOOST_DIR/include test_3d_ndarray.cc
    price@neverland:~/test/andreas $ ./test_3d_ndarray 
    testArray.getShape() = (10,10,10,)
    testArray[ndarray::view(0)()(1) = [       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    testView.getShape() = (10,)
    testView = [       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    Iterator-based size: 100
    testView via iterator: 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
    test_3d_ndarray: test_3d_ndarray.cc:19: int main(): Assertion `testView.end() - testView.begin() == testView.getShape()[0]' failed.
    Aborted (core dumped)

**Comment by PaulPrice** [comment]
Also fails on g++ 4.6.4 with ndarray from HSC.

**Comment by TallJimbo** [comment]
So, the bug here is that this code compiles at all: the type you're using for the view is `Array<float,1,1>`, and that last `1` means "the last (only) dimension is contiguous" - but that's not true of the view you're creating, which has a stride of 10, not a stride of 1.  Contiguous arrays just use a raw pointer as an iterator, and as a result we're iterating over the last dimension as well as the middle one, instead of creating a strided iterator that skips over the last dimension.

The good news is that the workaround is thus extremely easy; just use this instead to create the view:
```
ndarray::Array<float,1,0> testView = testArray[ndarray::view(0)()(1)];
```
That final `0` says that the array is not contiguous.

**Comment by ziggyman** [comment]
Good news, but this still doesn't explain why 
`std::cout << "testView = " << testView << std::endl;`
returns `100` elements, not `10`

**Comment by TallJimbo** [comment]
> Good news, but this still doesn't explain why 
std::cout << "testView = " << testView << std::endl;
returns 100 elements, not 10

It does explain it, but I didn't do a good job of explaining why.  The problem is that the return type of this view operation is incorrect - it returns an `Array<float,1,1>` instead of an `Array<float,1,0>`.  The iterator type for the former is just a pointer, while the iterator for the latter is a `StridedIterator` that points to the exact same pointer, but jumps 10 elements (in memory) at a time instead of just one.  So for operations that rely on the iterators (such as stringification), using the wrong iterator means it takes 10x as many steps to get to the endpoint.

**Comment by TallJimbo** [comment]
Found and fixed an off-by-one bug in the computation of view contiguousness.  I also improved up the unit test coverage for this considerably.
