### ISSUE TITLE
trying out pybind11

### ISSUE THREAD

**Issue by nbecker** [ndarray/ndarray#52]
I tried the following:
```c++
#include <numpy/ndarrayobject.h>
#include <ndarray/pybind11.h>
#include <boost/numpy.hpp>

namespace py = pybind11;
namespace nd=ndarray;

void doubler (nd::Array<double,2,2> & in) {
  for (int row = 0; row < in.getShape()[0]; ++row) {
    for (int col = 0; col < in.getShape()[1]; ++col) {
      in(row,col) *= 2;
    }
  }
}

PYBIND11_PLUGIN(test1) {
  boost::numpy::initialize();
  py::module m("example", "pybind11 example plugin");

    m.def("doubler", &doubler);
    return m.ptr();
}
```

```python
from test1 import doubler

import numpy as np
x = np.arange (10, dtype=float)
y = x.reshape (5,2)
#doubler(y)
```

If the commented line 'doubler(y)' is executed, I get segfault.

Am I using pybind11 incorrectly here?

**Comment by TallJimbo** [comment]
The `pybind11` bindings don't use `boost::numpy`, and hence I don't think the `boost::numpy::initialize()` line will setup the NumPy C API for them correctly.  We really need to clean that up (probably by using pybind11's buffer-interface hooks for NumPy rather than the NumPy C API), but for now I think you need to `#include` the NumPy headers and call `import_array` yourself, as described in the NumPy C API docs.

**Comment by nbecker** [comment]
OK, got that working, thanks!

So using ndarray with pybind11 interface, there is no need to build/link to libboost_numpy.so?  That would be a big improvement.

**Comment by TallJimbo** [comment]
Correct.  The penalty is that ugly bit of initialization in every file, and I hope to eventually make that go away too.
